spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

    kafka:
      port: 9092
      host: localhost

    channel:
      follower:
        name: follower_channel
      mentorship:
        name: mentorship_channel
      goal_complete:
        name: goal_complete_channel
      profile_view:
        name: profile_view_channel
      premium_bought:
        name: premium_bought_channel
      user_ban_channel:
        name: user_ban_channel

  profiles:
    active: test

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8090
  servlet:
    context-path: /api/v1

logging:
  level:
    root: info

premium:
  scheduler:
    expired-premium-remover:
      cron: 0 0 * * *

project-service:
  host: localhost
  port:

payment-service:
  host: localhost
  port:

aws:
  accessKey: access_key
  secretKey: secret_key
  region: bucket_region

services:
  s3:
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: user-bucket
    isMocked: true
    maxSizeBytes: 5242880
    smallSize: 170
    largeSize: 1080

goals:
  limit:
    max-per-user: 3
  invitations:
    max-per-user: 3

mentorship:
  request:
    time-period-for-single-request: 3

spring.servlet.multipart.max-file-size: 10KB

scheduler:
  clearEvents:
    cronExpression: "0 0 0 * * ?" # Каждый день в полночь

batchSize:
  eventDeletion: 1000

randomAvatar:
  url: https://api.dicebear.com/8.x/pixel-art/jpg?seed=
