spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8098

services:
  user-service:
    name: user-service
    host: http://localhost
    port: 8090
  project-service:
    name: project-service
    host: http://localhost
    port: 8092

logging:
  level:
    root: info

api:
  version: v1

scheduling:
  account-number-generation:
    amounts:
      INDIVIDUAL: 500
      SAVINGS: 200
      CORPORATE: 100
      INVESTMENT: 100
    cron: "0 0 * * * ?" #every day in 00:00